EF.F....E..FF.....F.FF....F.
======================================================================
ERROR: test__countingsort__worksForStringList (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_sorts.py", line 73, in test__countingsort__worksForStringList
    self.assertEqual(sorted(string_list), function(string_list) )
  File "/Users/timothycampbell/Documents/Clemson/CPSC873/Github/Python/sorts/countingsort.py", line 20, in countSort
    count[ord(i)] += 1
TypeError: ord() expected a character, but string of length 3 found

======================================================================
ERROR: test__mostSorts__workForIntLists_2_bucket_sort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/usr/local/lib/python3.5/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "test_sorts.py", line 37, in test__mostSorts__workForIntLists
    module = __import__("sorts."+sort_file_name, fromlist=[""])
  File "/Users/timothycampbell/Documents/Clemson/CPSC873/Github/Python/sorts/bucket_sort.py", line 16, in <module>
    from P26_InsertionSort import insertionSort
ImportError: No module named 'P26_InsertionSort'

======================================================================
FAIL: test__mostSorts__workForIntLists_0_bogosort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/usr/local/lib/python3.5/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "test_sorts.py", line 44, in test__mostSorts__workForIntLists
    self.assertEqual(sorted(i), function(i) )
  File "/Users/timothycampbell/Documents/Clemson/CPSC873/Github/Python/sorts/bogosort.py", line 38, in bogosort
    random.shuffle(collection)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/random.py", line 272, in shuffle
    x[i], x[j] = x[j], x[i]
  File "/usr/local/lib/python3.5/site-packages/timeout_decorator/timeout_decorator.py", line 72, in handler
    _raise_exception(timeout_exception, exception_message)
  File "/usr/local/lib/python3.5/site-packages/timeout_decorator/timeout_decorator.py", line 45, in _raise_exception
    raise exception()
timeout_decorator.timeout_decorator.TimeoutError: 'Timed Out'

======================================================================
FAIL: test__mostSorts__workForIntLists_11_radix_sort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/usr/local/lib/python3.5/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "test_sorts.py", line 44, in test__mostSorts__workForIntLists
    self.assertEqual(sorted(i), function(i) )
AssertionError: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12[344 chars], 99] != None

======================================================================
FAIL: test__mostSorts__workForIntLists_5_cyclesort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/usr/local/lib/python3.5/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "test_sorts.py", line 44, in test__mostSorts__workForIntLists
    self.assertEqual(sorted(i), function(i) )
AssertionError: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12[344 chars], 99] != 100

======================================================================
FAIL: test__mostSorts__workForIntLists_6_gnome_sort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/usr/local/lib/python3.5/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "test_sorts.py", line 44, in test__mostSorts__workForIntLists
    self.assertEqual(sorted(i), function(i) )
AssertionError: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12[344 chars], 99] != None

======================================================================
FAIL: test__someSorts__workForFloatLists_11_timsort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "test_sorts.py", line 66, in test__someSorts__workForFloatLists
    self.assertEqual(sorted(doubles_random), function(doubles_random) )
AssertionError: Lists differ: [0.024505255503901813, 0.030699321824596004, [1963 chars]1385] != [0.030699321824596004, 0.11725019556642313, 0[1472 chars]1385]

First differing element 0:
0.024505255503901813
0.030699321824596004

First list contains 24 additional elements.
First extra element 76:
0.710911660913507

Diff is 2348 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test__someSorts__workForFloatLists_2_cyclesort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "test_sorts.py", line 66, in test__someSorts__workForFloatLists
    self.assertEqual(sorted(doubles_random), function(doubles_random) )
AssertionError: [0.01945796301201108, 0.03530248733830199[1983 chars]4061] != 100

======================================================================
FAIL: test__someSorts__workForFloatLists_3_gnome_sort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "test_sorts.py", line 66, in test__someSorts__workForFloatLists
    self.assertEqual(sorted(doubles_random), function(doubles_random) )
AssertionError: [0.007987644313455333, 0.0224892357503481[1970 chars]8324] != None

======================================================================
FAIL: test__someSorts__workForFloatLists_8_radix_sort (__main__.TestSorts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "test_sorts.py", line 66, in test__someSorts__workForFloatLists
    self.assertEqual(sorted(doubles_random), function(doubles_random) )
AssertionError: [0.0087360446771797, 0.008773283231416129[1984 chars]3347] != None

----------------------------------------------------------------------
Ran 28 tests in 5.040s

FAILED (failures=8, errors=2)
